package com.ndh.ShopTechnology.dto.response.task;

import com.ndh.ShopTechnology.entities.task.TaskEntity;
import com.ndh.ShopTechnology.enums.task.*;
import lombok.Builder;
import lombok.Data;
import java.util.Date;

@Data @Builder
public class TaskResponse {
    private Long id;
    private Long boardId;
    private TaskStatus status;
    private TaskPriority priority;
    private TaskType taskType;
    private Long departmentId;
    private String title;
    private String description;
    private AssigneeInfo creator;
    private AssigneeInfo assignee;
    private Date dueDate;
    private Date startedAt;
    private Date completedAt;
    private Integer position;
    private TaskSourceType sourceType;
    private Long sourceId;
    private Boolean isAutoGenerated;
    private Date createdDate;
    private Date modifiedDate;

    /** Tổng hợp từ checklists */
    private ChecklistSummary checklistSummary;
    private long commentCount;
    private long attachmentCount;

    @Data @Builder
    public static class AssigneeInfo {
        private Long id;
        private String username;
        private String fullName;
        private String avatar;
    }

    @Data @Builder
    public static class ChecklistSummary {
        private int total;
        private int done;
        public int getPercentage() {
            return total == 0 ? 0 : Math.round(done * 100f / total);
        }
    }

    public static TaskResponse fromEntity(TaskEntity e) {
        if (e == null) return null;
        return TaskResponse.builder()
            .id(e.getId())
            .boardId(e.getBoardId())
            .status(e.getStatus())
            .priority(e.getPriority())
            .taskType(e.getTaskType())
            .departmentId(e.getDepartmentId())
            .title(e.getTitle())
            .description(e.getDescription())
            .creator(e.getCreator() == null ? null : AssigneeInfo.builder()
                .id(e.getCreator().getId())
                .username(e.getCreator().getUsername())
                .fullName(e.getCreator().getUserInfo() != null ? e.getCreator().getUserInfo().getFullName() : null)
                .avatar(e.getCreator().getUserInfo() != null ? e.getCreator().getUserInfo().getAvatar() : null)
                .build())
            .assignee(e.getAssignee() == null ? null : AssigneeInfo.builder()
                .id(e.getAssignee().getId())
                .username(e.getAssignee().getUsername())
                .fullName(e.getAssignee().getUserInfo() != null ? e.getAssignee().getUserInfo().getFullName() : null)
                .avatar(e.getAssignee().getUserInfo() != null ? e.getAssignee().getUserInfo().getAvatar() : null)
                .build())
            .dueDate(e.getDueDate())
            .startedAt(e.getStartedAt())
            .completedAt(e.getCompletedAt())
            .position(e.getPosition())
            .sourceType(e.getSourceType())
            .sourceId(e.getSourceId())
            .isAutoGenerated(e.getIsAutoGenerated())
            .createdDate(e.getCreatedDate())
            .modifiedDate(e.getModifiedDate())
            .build();
    }
}
