package com.ndh.ShopTechnology.entities.task;

import com.ndh.ShopTechnology.entities.BaseEntity;
import com.ndh.ShopTechnology.entities.user.UserEntity;
import com.ndh.ShopTechnology.enums.task.*;
import jakarta.persistence.*;
import lombok.*;

import java.util.Date;
import java.util.List;

@Getter @Setter @Builder @NoArgsConstructor @AllArgsConstructor
@Entity(name = "Task")
@Table(name = "task",
    indexes = {
        @Index(name = "idx_task_board_status",   columnList = "board_id, status, is_deleted"),
        @Index(name = "idx_task_board_position", columnList = "board_id, status, position"),
        @Index(name = "idx_task_assignee",       columnList = "assignee_id, status, is_deleted"),
        @Index(name = "idx_task_due_date",       columnList = "due_date, status, is_deleted"),
        @Index(name = "idx_task_source",         columnList = "source_type, source_id"),
        @Index(name = "idx_task_type",           columnList = "task_type, status"),
        @Index(name = "idx_task_priority",       columnList = "priority, status, is_deleted"),
    })
public class TaskEntity extends BaseEntity {

    @Column(name = "board_id", nullable = false)
    private Long boardId;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private TaskStatus status = TaskStatus.NEW;

    @Enumerated(EnumType.STRING)
    @Column(name = "priority", nullable = false, length = 10)
    @Builder.Default
    private TaskPriority priority = TaskPriority.MEDIUM;

    @Enumerated(EnumType.STRING)
    @Column(name = "task_type", nullable = false, length = 30)
    @Builder.Default
    private TaskType taskType = TaskType.OTHER;

    @Column(name = "department_id")
    private Long departmentId;

    @Column(name = "title", nullable = false, length = 255)
    private String title;

    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "creator_id", nullable = false, foreignKey = @ForeignKey(name = "fk_task_creator"))
    private UserEntity creator;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assignee_id", foreignKey = @ForeignKey(name = "fk_task_assignee"))
    private UserEntity assignee;

    @Column(name = "due_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date dueDate;

    @Column(name = "started_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date startedAt;

    @Column(name = "completed_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date completedAt;

    @Column(name = "position", nullable = false)
    @Builder.Default
    private Integer position = 0;

    @Enumerated(EnumType.STRING)
    @Column(name = "source_type", length = 30)
    private TaskSourceType sourceType;

    @Column(name = "source_id")
    private Long sourceId;

    @Column(name = "is_auto_generated", nullable = false)
    @Builder.Default
    private Boolean isAutoGenerated = false;

    @Column(name = "is_deleted", nullable = false)
    @Builder.Default
    private Boolean isDeleted = false;

    @Column(name = "deleted_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date deletedAt;

    @Column(name = "deleted_by", length = 100)
    private String deletedBy;

    /* ── Relations (lazy) ── */

    @OneToMany(mappedBy = "task", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private List<TaskParticipantEntity> participants;

    @OneToMany(mappedBy = "task", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private List<TaskCommentEntity> comments;

    @OneToMany(mappedBy = "task", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private List<TaskChecklistEntity> checklists;

    @OneToMany(mappedBy = "task", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private List<TaskAttachmentEntity> attachments;

    @OneToMany(mappedBy = "task", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private List<TaskStatusHistoryEntity> statusHistory;
}
